name: Vercel webhook
on: push
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Calling webhook
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.VERCEL_WEBHOOK }}
        method: 'POST'